url: https://www.stackfolk.co.uk
baseurl: 

# Site settings
title: "StackFolk: |" 
email: 
description: "DevOps practitioners, software engineers, agile practitioners"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jesper Markenstam
  pic: 1
  position: Director (also DevOps engineer in public sector)
  social:
    - title: linkedin
      url: http://uk.linkedin.com/in/jmarkenstam/en
#    - title: envelope-o
#      url: 
    - title: phone
      url: tel:+447787152504

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stackfolk
#  - title: linkedin
#    url: http://www.linkedin.com

# Postal address (add as many lines as necessary)
address:
  - line: 22 Hassocks Road
  - line: London
  - line: SW16 5EX

# Build settings
markdown: kramdown
permalink: pretty
